### ISSUE TITLE
[Java] ConcreteClassifier reloading brings up new and unregistered object

### ISSUE THREAD

**Issue by JanWittler** [vitruv-tools/Vitruv-Domains-ComponentBasedSystems#97]
In the Java domain, when reloading a `Class` without a superclass, it's `defaultExtends` is automatically populated with a reference to `Object`. Since this reference was not present in the original object (`defaultExtends == null`), our `UUIDGeneratorAndResolverImpl` does not know it and throws an error in `registerEObject(EObject)`.
Reloading some instance is a valid operation. As an example, it should happen after propagating from domain B to domain A and then accessing some object from domain A. Without reloading, it is not guaranteed to access the latest version of the object.

I would classify this rather as an issue with JaMoPP / emftext.java than with our implementation (as `defaultExtends` should be populated in first place too). However, the [JaMoPP repository](https://github.com/DevBoost/JaMoPP) looks abandoned so I thought it worthy to discuss here whether to try to fix it in JaMoPP or provide some workaround in Vitruv which maybe applies to other scenarios too (of which I can't imagine some yet).

### Example code
```Xtend
//precondition: existing var of Class type as in JavaToUmlClassTest.xtend
println(jClass.defaultExtends) // prints null
val uri = EcoreUtil.getURI(jClass)
renewResourceCache
jClass = uri.trimFragment.resourceAt?.getEObject(uri.fragment) as Class
print(jClass.defaultExtends) // prints org.emftext.language.java.types.impl.ClassifierReferenceImpl
```

**Comment by HeikoKlare** [comment]
We have discussed the issue some time ago and I think we had some functionality in previous versions of the `UuidGeneratorAndResolverImpl` which made it robust against this type of problem. However, it is not surprising to me that the current implementation does not support that case anymore, and obviously we did not provide regression tests for that case (which is also not that easy because it relies on specific serialization logic of JaMoPP).

As you mention correctly, this is essentially an issue of JaMoPP, because we (in my opinion reasonably) assume that saving some model and reloading it leads to equal results. This invariant is, however, not fulfilled by JaMoPP in at least two cases that I am aware of:
1. The `name` of a `CompilationUnit` after reload is the fully qualified name with a `.java` suffix, whereas it also accepts, for example, the simple name of the contained classifier when saving.
2. The `defaultExtends` is a `ClassifierReference` to `Object` after loading if it was `null` when saving.

Maybe there are more cases, but these are the ones that I am aware of.

The question is whether our assumption regarding save/load equality is reasonable or not. If that is the case, we need to provide some adapter for JaMoPP that ensures it. In fact, either of the cases will only occur if you create a Java model by hand (instead of using a textual editor), which will unlikely ever be the case. In our case, the situation occurs during change propagation, but it would be easy to adapt it such that is generates proper `defaultExtends` entries, like it was updated to generate proper `name` entries in the compilation units. We could do the same in our application tests, in which Java code is created by model manipulation rather than textual code file editing. For example, in the `editortests` this problem will not occur.

**Comment by JanWittler** [comment]
I think it is reasonable to expect that save -> load is idempotent. However, I don't know if in practice this is something we can assume for all domains; or differently said if knowing that this might occur, we will leave the burden to the one integrating the problematic domain rather than providing some general-purpose logic / API for that problem.

Do I understand it correctly that you propose to adjust the consistency specification to address this issue? Since this issue popped up after it has been solved once ago, we can see that it is hard to test and thus hard to detect all cases where such a workaround is needed. If we use the consistency specifications to fix this, there is a high chance of missing some routine. Furthermore we would need to apply the workaround for every new consistency specification with the problematic domain.
Therefore I think it would make most sense to provide some functionality to fix this as part of the domain rather than  the application. Without having a specific code solution in mind, I can imagine that the `DomainAwareResource` could be a good extension point for it.

**Comment by HeikoKlare** [comment]
Actually, we have not provided a fix, but I think the issue was "fixed" (or more precisely somehow hidden) by the way the `UuidGeneratorAndResolverImpl` worked after some modifications to it (but I am sure w.r.t. anymore, maybe I am wrong).
Adapting the consistency specifications and providing according regression tests should "solve" the problem sustainably. Since this only affects the `defaultExtends` reference right now, it would be sufficient to provide a utility for the complete Java domain for creating a `Class`, which then delivers a `Class` with the `defaultExtends` reference set properly. Of course, we then need to replace every class creation in the consistency specifications accordingly.

As you propose, we may also provide some mechanism to adapt the domain and somehow hide the behavior, or we may even adapt the change propagation mechanism to perform an additional state-based propagation after a change-based propagation, which then propagates the changes introduced by reloading a resource. However, I am not that conviced that this is worth it as long as there is only a single scenario where we have that issue.
We might instead introduce a validation of our assumed invariant in the framework that notifies us whenever it the invariant not fulfilled. Such a validation could simply reload the saved resources after change propagation and compare them with the resources before saving. A benefit would be that if the invariant is violated in other cases than the `defaultExtends` reference, we would get notified about that.

**Comment by JanWittler** [comment]
I discovered another case where the reloading invariant is not hold, which looks to me like a fundamental issue with JaMoPP and which - I think from my current understanding - can not be fixed by adjusting the consistency specifications.
When reloading a class that references another class, the reference is incorrectly loaded. Instead of referencing the appropriate class (like it was done before reload), the object now references a `ClassImpl` with proxy eProxyURI `file:/<path>/<class>.java#EMFTEXT_INTERNAL_URI_FRAGMENT_<internalCounter>_<referencedClassName>)`. However the eResource is `null` and thus the object cannot be resolved.
I spent significant time to check whether our setup of the JaMoPP model as part of the reactions is correct but could not find any flaw (but not 100% sure as there is no JaMoPP documentation) and the source code looks correct too. Therefore I think the only possibility to address this is to insert a Java preprocessor that resolves such proxies automatically. Right now reloading and accessing any Java resource with a custom type in it results in a crash in `UUIDGeneratorAndResolverImpl#getUuid(EObject)`

### Example
<details><summary>Class A.java</summary>

```Java
package example;

public Class A {
}
```
</details>

<details><summary>Class B.java</summary>

```Java
package example;

import example.A;

public class B {
  private A a;
}
```
</details>

**Comment by HeikoKlare** [comment]
As far as I know, JaMoPP does, by default, not resolve proxies to other resources. This is reasonable, because otherwise you would probably face high load times for single files if all references types need to be loaded as well. But I think you could force the resource set to resolve proxies upon loading a resource in case you need it. 
I have to admit that I do not yet understand when the situation having proxy elements occurs and trying to resolve UUIDs for them, and why it becomes problematic. Within the `VirtualModel`, all models should be loaded within the resource set and thus should be accessible, and a reload should never be performed, so the problem should not occur there. However, you mentioned that we cannot solve that issue by adapting the consistency specifications, so it actually seems to be about the resources within the `VirtualModel`.

**Comment by JanWittler** [comment]
> I discovered another case where the reloading invariant is not hold, which looks to me like a fundamental issue with JaMoPP and which - I think from my current understanding - can not be fixed by adjusting the consistency specifications.
> When reloading a class that references another class, the reference is incorrectly loaded. Instead of referencing the appropriate class (like it was done before reload), the object now references a `ClassImpl` with proxy eProxyURI `file:/<path>/<class>.java#EMFTEXT_INTERNAL_URI_FRAGMENT_<internalCounter>_<referencedClassName>)`. However the eResource is `null` and thus the object cannot be resolved.

This seems to be linked to [Vitruv#464](https://github.com/vitruv-tools/Vitruv/issues/464) and thus can be fixed by adjusting the order in which resources are accessed.

> Of course, we then need to replace every class creation in the consistency specifications accordingly.

Though there is no scenario anymore that cannot be solved by adjusting the consistency specifications, I am still not in favor of this solution. Mainly because this again scatters a workaround across various places (all different consistency specifications), and I think with the recent refactoring to UUIDs we saw how badly such scattered workarounds can be removed. 

> I have to admit that I do not yet understand when the situation having proxy elements occurs and trying to resolve UUIDs for them, and why it becomes problematic. Within the VirtualModel, all models should be loaded within the resource set and thus should be accessible, and a reload should never be performed, so the problem should not occur there.

To name one specific scenario where the problem is occurring for me: I am creating a model in the UML domain, propagate changes which create Java classes and then access and modify these Java classes. In that case the `TestView` does not have the Java classes yet in its `resourceSet` thus they are loaded from file - which basically works the same as a reload. (Maybe the new View architecture will resolve this automatically as it probably changes how views are accessing models of the VSUM.)

**Comment by HeikoKlare** [comment]
> Though there is no scenario anymore that cannot be solved by adjusting the consistency specifications, I am still not in favor of this solution. Mainly because this again scatters a workaround across various places 

It would not scatter the workaround if we provide the according instantiation functionality at a single place (i.e., a method for creating a classifier with the `defaultExtends` reference properly set). This is what the JaMoPP factory should actually provide and would thus be equivalent to using a properly implemented JaMoPP factory. In addition, the model validation should fail whenever the reference is not set properly. To provide the instantiation functionality, we could replace the JaMoPP factory in the Java domain such that it always generates a valid classifier (we have done something comparable for UML resources before).

> To name one specific scenario where the problem is occurring for me: I am creating a model in the UML domain, propagate changes which create Java classes and then access and modify these Java classes.

Okay, I see the problem. This is, however, more related to how UUID loading works rather than a JaMoPP-specific problem. Although this is not an immediate solution, I would expect the problem to be solved when replacing UUIDs with more lightweight IDs in https://github.com/vitruv-tools/Vitruv/pull/467 (or in the worst case then to occur in a different way).

**Comment by JanWittler** [comment]
> In addition, the model validation should fail whenever the reference is not set properly.

This would be beneficial. My greatest concern with the custom factory method is that currently there are a lot of workarounds or "shared knowledge" which is not documented and which makes it really hard for newcomers to _make it right_. If we provide some custom factory, it is likely that newcomers will not be aware of it and still use the default instantiation. If we can provide some validation that gives an error (and best a hint to the factory), I think this will solve the issue.

**Comment by HeikoKlare** [comment]
I am not sure whether the discussed issue is still relevant/present after merging https://github.com/vitruv-tools/Vitruv/pull/467.
We have replaced UUIDs with more lightweight IDs, which do not have the implicit assumption to be created for every object upon recognizing a create change. Thus, I would expect `defaultExtends` only being set after a reload of the model not to be an issue anymore.
As far as I understand, the changes may also solve the issue with proxy elements, because it should be possible to calculate IDs for proxy elements now and as soon as the proxies are resolved upon loading their resource, the IDs should be updated properly.

If you have some previously problematic scenarios at hand, it would be nice if you could validate them against the recent framework changes to identify whether some of the problems are still present or implicitly solved by removing the strong assumptions our UUID mechanism made.

**Comment by JanWittler** [comment]
Validated against the problematic scenarios that the removal of UUID resolved the problem
